rm(list=ls())
a<-read.table('pedago.txt')
attach(a)
boxplot(note~pedago)
stripchart(note~pedago,method='stack',vertical=T)
tapply(note,pedago,mean)
tapply(note,pedago,sd)
tapply(note,pedago,summary)
barplot(t(tapply(note,pedago,mean)))

m<-aov(note~pedago)
summary(m)
TukeyHSD(m)
plot(TukeyHSD(m))
